# Project metadata
name: 'DBT_SF_DWH2024'        # The name of the project. It should be in lowercase and contain only characters and underscores.
version: '1.0.0'              # The version of the project.

# Profile configuration
profile: 'DBT_SF_DWH2024'     # The profile that dbt uses for this project.

# File paths configuration
model-paths: ["models"]       # Directory where dbt looks for model files.
analysis-paths: ["analyses"]  # Directory where dbt looks for analysis files.
test-paths: ["tests"]         # Directory where dbt looks for test files.
seed-paths: ["seeds"]         # Directory where dbt looks for seed files.
macro-paths: ["macros"]       # Directory where dbt looks for macro files.
snapshot-paths: ["snapshots"] # Directory where dbt looks for snapshot files.

# Clean targets configuration
clean-targets:                
  - "target"                 # Directory to be removed by `dbt clean`.
  - "dbt_packages"           # Directory to be removed by `dbt clean`.

# Models configuration
# This section configures default settings for models in different directories.
models:
  mart:
    +materialized: view       # Models in the 'mart' directory will be materialized as views.
    +schema: DM               # Models in the 'mart' directory will be created in the 'DM' schema.
    +persist_docs:
      relation: true          # Persist documentation for the relation (model).
      columns: true           # Persist documentation for the columns.

  operational_data_storage:
    +materialized: view       # Models in the 'operational_data_storage' directory will be materialized as views.
    +schema: ODS              # Models in the 'operational_data_storage' directory will be created in the 'ODS' schema.
    +persist_docs:
      relation: true          # Persist documentation for the relation (model).

  staging:
    +materialized: view       # Models in the 'staging' directory will be materialized as views.
    +schema: STG              # Models in the 'staging' directory will be created in the 'STG' schema.
    +persist_docs:
      relation: true          # Persist documentation for the relation (model).
      columns: true           # Persist documentation for the columns.

  testing:
    +materialized: view       # Models in the 'testing' directory will be materialized as views.
    +schema: tmp              # Models in the 'testing' directory will be created in the 'tmp' schema.
    +persist_docs:
      relation: true          # Persist documentation for the relation (model).
