name: DBT Workflow

on: [push, pull_request]

jobs:
  dbt_run:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install dbt-snowflake dbt-expectations

      - name: Create dbt profile directory
        run: |
          New-Item -Path "$env:USERPROFILE\.dbt" -ItemType Directory -Force
          New-Item -Path "$env:USERPROFILE\.dbt\profiles.yml" -ItemType File -Force

      - name: Configure dbt profile
        run: |
          $profile = @"
          DBT_SF_DWH2024:
            outputs:
              dev:
                type: snowflake
                account: '${{ secrets.SNOWFLAKE_ACCOUNT }}'
                user: '${{ secrets.SNOWFLAKE_USER }}'
                password: '${{ secrets.SNOWFLAKE_PASSWORD }}'
                role: '${{ secrets.SNOWFLAKE_ROLE }}'
                database: '${{ secrets.SNOWFLAKE_DATABASE }}'
                warehouse: '${{ secrets.SNOWFLAKE_WAREHOUSE }}'
                schema: '${{ secrets.SNOWFLAKE_SCHEMA }}'
                threads: 8
                client_session_keep_alive: False
            target: dev
          "@
          $profile | Out-File -FilePath "$env:USERPROFILE\.dbt\profiles.yml"

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.dbt
            ./.dbt
            ./target
          key: ${{ runner.os }}-dbt-${{ hashFiles('**/dbt_project.yml') }}
          restore-keys: |
            ${{ runner.os }}-dbt-

      - name: Run dbt seed
        run: dbt seed --profiles-dir "$env:USERPROFILE\.dbt"

      - name: Run dbt run
        run: dbt run --profiles-dir "$env:USERPROFILE\.dbt"

      - name: Run dbt test
        run: dbt test --profiles-dir "$env:USERPROFILE\.dbt"

      - name: Generate dbt documentation
        run: dbt docs generate --profiles-dir "$env:USERPROFILE\.dbt"

      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dbt_docs
          path: target/
